### PR TITLE
add contributors guide

### PR DESCRIPTION
**Pull request by oraNod**

### CODE REVIEW

**Comment by samccann** [comment]
fwiw this will clash with @GregSutcliffe PR https://github.com/ansible/ansible-documentation/pull/598

**Comment by samccann** [comment]
oh ignore my noise... separate repo doh!  But I think it's  worth tracking that PR and incorporating it here once the dust settles (aka it gets merged).

**Review by samccann — APPROVED** [review]
LGTM

**Comment by oraNod** [comment]
> oh ignore my noise... separate repo doh! But I think it's worth tracking that PR and incorporating it here once the dust settles (aka it gets merged).

thanks and no worries. yeah I've been keeping an eye on the DCO thing (basically lurking) and will incorporate all that into this repo too. but will let the community do their thing first.

**Pull request merged**
