### PR TITLE
Add community ees to ecosystem

### PR DESCRIPTION
**Pull request by oraNod**
As discussed in #4 this PR adds the community EEs to the ecosystem page.

### CODE REVIEW

**Comment by oraNod** [comment]
Hmm. I don't actually see it in the checks but here is the preview build: https://ansible--5.org.readthedocs.build/en/5/ecosystem.html

**Review by Andersson007 — APPROVED** [review]
LGTM
Will having tools such as AWX/Controller, Navigator and Builder that use EEs mentioned here be too much?

**Comment by oraNod** [comment]
> LGTM Will having tools such as AWX/Controller, Navigator and Builder that use EEs mentioned here be too much?

I don't think so at all. That's part of the point of the ecosystem docs. Although I think we should do that as a follow on PR.

**Comment by Andersson007** [comment]
> > LGTM Will having tools such as AWX/Controller, Navigator and Builder that use EEs mentioned here be too much?
> 
> I don't think so at all. That's part of the point of the ecosystem docs. Although I think we should do that as a follow on PR.

@oraNod wfm, thanks!

**Pull request merged**
